### ISSUE TITLE
Systray application fails on Windows "panic: Unable to create main window: TTM_ADDTOOL failed"

### ISSUE THREAD

**Issue by seannowotny** [getlantern/systray#124]
Running

```cmd
env GO111MODULE=on go run main.go
```

on Windows 10 64bit using go1.13.8 fails on following code

```go
package main

import "github.com/getlantern/systray"

func main() {
    systray.Run(onReady, onExit)
}

func onReady() {

}

func onExit() {

}
```

Log:

```cmd
go: finding github.com/getlantern/systray latest
go: downloading github.com/getlantern/systray v0.0.0-20200109124156-9abdfb6448b3
go: extracting github.com/getlantern/systray v0.0.0-20200109124156-9abdfb6448b3
go: downloading github.com/getlantern/golog v0.0.0-20190830074920-4ef2e798c2d7
go: downloading github.com/lxn/walk v0.0.0-20191113135339-bf589de20b3c
go: extracting github.com/getlantern/golog v0.0.0-20190830074920-4ef2e798c2d7
go: downloading github.com/oxtoacart/bpool v0.0.0-20190530202638-03653db5a59c
go: downloading github.com/getlantern/hidden v0.0.0-20190325191715-f02dbb02be55
go: downloading github.com/getlantern/errors v0.0.0-20190325191628-abdb3e3e36f7
go: downloading github.com/getlantern/ops v0.0.0-20190325191751-d70cb0d6f85f
go: extracting github.com/getlantern/hidden v0.0.0-20190325191715-f02dbb02be55
go: extracting github.com/getlantern/ops v0.0.0-20190325191751-d70cb0d6f85f
go: extracting github.com/oxtoacart/bpool v0.0.0-20190530202638-03653db5a59c
go: extracting github.com/getlantern/errors v0.0.0-20190325191628-abdb3e3e36f7
go: downloading github.com/getlantern/hex v0.0.0-20190417191902-c6586a6fe0b7
go: downloading github.com/getlantern/context v0.0.0-20190109183933-c447772a6520
go: downloading github.com/go-stack/stack v1.8.0
go: extracting github.com/getlantern/hex v0.0.0-20190417191902-c6586a6fe0b7
go: extracting github.com/getlantern/context v0.0.0-20190109183933-c447772a6520
go: extracting github.com/go-stack/stack v1.8.0
go: extracting github.com/lxn/walk v0.0.0-20191113135339-bf589de20b3c
go: downloading golang.org/x/sys v0.0.0-20190919044723-0c1ff786ef13
go: downloading gopkg.in/Knetic/govaluate.v3 v3.0.0
go: downloading github.com/lxn/win v0.0.0-20191106123917-121afc750dd3
go: extracting gopkg.in/Knetic/govaluate.v3 v3.0.0
go: extracting github.com/lxn/win v0.0.0-20191106123917-121afc750dd3
go: extracting golang.org/x/sys v0.0.0-20190919044723-0c1ff786ef13
go: finding github.com/getlantern/golog v0.0.0-20190830074920-4ef2e798c2d7
go: finding github.com/getlantern/errors v0.0.0-20190325191628-abdb3e3e36f7
go: finding github.com/getlantern/context v0.0.0-20190109183933-c447772a6520
go: finding github.com/getlantern/hidden v0.0.0-20190325191715-f02dbb02be55
go: finding github.com/getlantern/hex v0.0.0-20190417191902-c6586a6fe0b7
go: finding github.com/getlantern/ops v0.0.0-20190325191751-d70cb0d6f85f
go: finding github.com/go-stack/stack v1.8.0
go: finding github.com/oxtoacart/bpool v0.0.0-20190530202638-03653db5a59c
go: finding github.com/lxn/walk v0.0.0-20191113135339-bf589de20b3c
go: finding github.com/lxn/win v0.0.0-20191106123917-121afc750dd3
go: finding golang.org/x/sys v0.0.0-20190919044723-0c1ff786ef13
go: finding gopkg.in/Knetic/govaluate.v3 v3.0.0
panic: Unable to create main window: TTM_ADDTOOL failed

Stack:
goroutine 1 [running, locked to thread]:
runtime/debug.Stack(0x432, 0x0, 0xc0000a9810)
        c:/go/src/runtime/debug/stack.go:24 +0xa4
github.com/lxn/walk.newErr(...)
        C:/gocode/pkg/mod/github.com/lxn/walk@v0.0.0-20191113135339-bf589de20b3c/error.go:81
github.com/lxn/walk.newError(0x8c4617, 0x12, 0x0, 0xc0000a9810)
        C:/gocode/pkg/mod/github.com/lxn/walk@v0.0.0-20191113135339-bf589de20b3c/error.go:85 +0x2d
github.com/lxn/walk.(*ToolTip).addTool(0xc0000af400, 0x95ae40, 0xc000063c00, 0x95ae00, 0xc000063c00, 0xc0000a98c0)
        C:/gocode/pkg/mod/github.com/lxn/walk@v0.0.0-20191113135339-bf589de20b3c/tooltip.go:186 +0xed
github.com/lxn/walk.(*ToolTip).AddTool(...)
        C:/gocode/pkg/mod/github.com/lxn/walk@v0.0.0-20191113135339-bf589de20b3c/tooltip.go:164
github.com/lxn/walk.(*WidgetBase).init(0xc000063c00, 0x95ae40, 0xc000063c00, 0x95ae40, 0xc000063c00)
        C:/gocode/pkg/mod/github.com/lxn/walk@v0.0.0-20191113135339-bf589de20b3c/widget.go:137 +0xeb
github.com/lxn/walk.InitWindow(0xf28488, 0xc000063c00, 0x957b00, 0xc0000ec400, 0x8ca24a, 0x1c, 0x1000050000000, 0x0, 0x0)
        C:/gocode/pkg/mod/github.com/lxn/walk@v0.0.0-20191113135339-bf589de20b3c/window.go:637 +0x435
github.com/lxn/walk.InitWidget(0x95ae40, 0xc000063c00, 0x957b00, 0xc0000ec400, 0x8ca24a, 0x1c, 0x1000050000000, 0x8b99a0, 0xf28100)
        C:/gocode/pkg/mod/github.com/lxn/walk@v0.0.0-20191113135339-bf589de20b3c/widget.go:110 +0xc3
github.com/lxn/walk.NewCompositeWithStyle(0x957b00, 0xc0000ec400, 0xc000000000, 0x957b00, 0xc0000ec400, 0x95a500)
        C:/gocode/pkg/mod/github.com/lxn/walk@v0.0.0-20191113135339-bf589de20b3c/composite.go:30 +0xda
github.com/lxn/walk.NewComposite(0x95a500, 0xc0000ec400, 0xc0000ec400, 0x95a500, 0xc0000ec400)
        C:/gocode/pkg/mod/github.com/lxn/walk@v0.0.0-20191113135339-bf589de20b3c/composite.go:45 +0x68
github.com/lxn/walk.(*FormBase).init(0xc0000ec400, 0x95d260, 0xc0000ec400, 0x95d260, 0xc0000ec400)
        C:/gocode/pkg/mod/github.com/lxn/walk@v0.0.0-20191113135339-bf589de20b3c/form.go:105 +0x67
github.com/lxn/walk.InitWindow(0x957b00, 0xc0000ec400, 0x0, 0x0, 0x8caa3d, 0x1d, 0x1000000cf0000, 0x0, 0x0)
        C:/gocode/pkg/mod/github.com/lxn/walk@v0.0.0-20191113135339-bf589de20b3c/window.go:629 +0xb76
github.com/lxn/walk.NewMainWindowWithName(0x0, 0x0, 0x0, 0x0, 0x0)
        C:/gocode/pkg/mod/github.com/lxn/walk@v0.0.0-20191113135339-bf589de20b3c/mainwindow.go:41 +0xd1
github.com/lxn/walk.NewMainWindow(...)
        C:/gocode/pkg/mod/github.com/lxn/walk@v0.0.0-20191113135339-bf589de20b3c/mainwindow.go:34
github.com/getlantern/systray.nativeLoop(0x0, 0x0, 0x0, 0x0)
        C:/gocode/pkg/mod/github.com/getlantern/systray@v0.0.0-20200109124156-9abdfb6448b3/systray_windows.go:30 +0x42
github.com/getlantern/systray.RunWithAppWindow(0x0, 0x0, 0x0, 0x0, 0x8dd070, 0x8dd068)
        C:/gocode/pkg/mod/github.com/getlantern/systray@v0.0.0-20200109124156-9abdfb6448b3/systray.go:85 +0xb0
github.com/getlantern/systray.Run(...)
        C:/gocode/pkg/mod/github.com/getlantern/systray@v0.0.0-20200109124156-9abdfb6448b3/systray.go:56
main.main()
        C:/desktop/fyne/systray-devto/main.go:7 +0x4d


goroutine 1 [running, locked to thread]:
github.com/getlantern/systray.fail(...)
        C:/gocode/pkg/mod/github.com/getlantern/systray@v0.0.0-20200109124156-9abdfb6448b3/systray_windows.go:218
github.com/getlantern/systray.nativeLoop(0x0, 0x0, 0x0, 0x0)
        C:/gocode/pkg/mod/github.com/getlantern/systray@v0.0.0-20200109124156-9abdfb6448b3/systray_windows.go:32 +0x91d
github.com/getlantern/systray.RunWithAppWindow(0x0, 0x0, 0x0, 0x0, 0x8dd070, 0x8dd068)
        C:/gocode/pkg/mod/github.com/getlantern/systray@v0.0.0-20200109124156-9abdfb6448b3/systray.go:85 +0xb0
github.com/getlantern/systray.Run(...)
        C:/gocode/pkg/mod/github.com/getlantern/systray@v0.0.0-20200109124156-9abdfb6448b3/systray.go:56
main.main()
        C:/desktop/fyne/systray-devto/main.go:7 +0x4d
exit status 2
```

**Comment by Asp3ctus** [comment]
try bat script

go clean
set GOOS=windows
go build -ldflags -H=windowsgui

**Comment by joesis** [comment]
No longer relevant as the example doesn't use `lxn/walk` any more.
