### ISSUE TITLE
windows run example is error

### ISSUE THREAD

**Issue by d1y** [getlantern/systray#134]
```
$ go run .\example\main.go
panic: Unable to create main window: TTM_ADDTOOL failed

Stack:
goroutine 1 [running, locked to thread]:
runtime/debug.Stack(0x432, 0x0, 0xc0001077e8)
        C:/Go/src/runtime/debug/stack.go:24 +0xa4
github.com/lxn/walk.newErr(...)
        C:/Users/Administrator/go/pkg/mod/github.com/lxn/walk@v0.0.0-20191113135339-bf589de20b3c/error.go:81
github.com/lxn/walk.newError(0x8a6377, 0x12, 0x0, 0xc0001077e8)
        C:/Users/Administrator/go/pkg/mod/github.com/lxn/walk@v0.0.0-20191113135339-bf589de20b3c/error.go:85 +0x2d
github.com/lxn/walk.(*ToolTip).addTool(0xc00007b180, 0x940c20, 0xc000136a80, 0x940c00, 0xc000136a80, 0xc000107898)
        C:/Users/Administrator/go/pkg/mod/github.com/lxn/walk@v0.0.0-20191113135339-bf589de20b3c/tooltip.go:186 +0xed
github.com/lxn/walk.(*ToolTip).AddTool(...)
        C:/Users/Administrator/go/pkg/mod/github.com/lxn/walk@v0.0.0-20191113135339-bf589de20b3c/tooltip.go:164
github.com/lxn/walk.(*WidgetBase).init(0xc000136a80, 0x940c20, 0xc000136a80, 0x940c20, 0xc000136a80)
        C:/Users/Administrator/go/pkg/mod/github.com/lxn/walk@v0.0.0-20191113135339-bf589de20b3c/widget.go:137 +0xeb
github.com/lxn/walk.InitWindow(0x1074360, 0xc000136a80, 0x93d8e0, 0xc000158000, 0x8ac258, 0x1c, 0x1000050000000, 0x0, 0x0)
        C:/Users/Administrator/go/pkg/mod/github.com/lxn/walk@v0.0.0-20191113135339-bf589de20b3c/window.go:637 +0x42a
github.com/lxn/walk.InitWidget(0x940c20, 0xc000136a80, 0x93d8e0, 0xc000158000, 0x8ac258, 0x1c, 0x1000050000000, 0x89b4a0, 0x1074000)
        C:/Users/Administrator/go/pkg/mod/github.com/lxn/walk@v0.0.0-20191113135339-bf589de20b3c/widget.go:110 +0xc3
github.com/lxn/walk.NewCompositeWithStyle(0x93d8e0, 0xc000158000, 0xc000000000, 0x93d8e0, 0xc000158000, 0x9402e0)
        C:/Users/Administrator/go/pkg/mod/github.com/lxn/walk@v0.0.0-20191113135339-bf589de20b3c/composite.go:30 +0xda
github.com/lxn/walk.NewComposite(0x9402e0, 0xc000158000, 0xc000158000, 0x9402e0, 0xc000158000)
        C:/Users/Administrator/go/pkg/mod/github.com/lxn/walk@v0.0.0-20191113135339-bf589de20b3c/composite.go:45 +0x68
github.com/lxn/walk.(*FormBase).init(0xc000158000, 0x943040, 0xc000158000, 0x943040, 0xc000158000)
        C:/Users/Administrator/go/pkg/mod/github.com/lxn/walk@v0.0.0-20191113135339-bf589de20b3c/form.go:105 +0x67
github.com/lxn/walk.InitWindow(0x93d8e0, 0xc000158000, 0x0, 0x0, 0x8aca4b, 0x1d, 0x1000000cf0000, 0x0, 0x0)
        C:/Users/Administrator/go/pkg/mod/github.com/lxn/walk@v0.0.0-20191113135339-bf589de20b3c/window.go:629 +0xba5
github.com/lxn/walk.NewMainWindowWithName(0x0, 0x0, 0x0, 0x0, 0x0)
        C:/Users/Administrator/go/pkg/mod/github.com/lxn/walk@v0.0.0-20191113135339-bf589de20b3c/mainwindow.go:41 +0xd2
github.com/lxn/walk.NewMainWindow(...)
        C:/Users/Administrator/go/pkg/mod/github.com/lxn/walk@v0.0.0-20191113135339-bf589de20b3c/mainwindow.go:34
github.com/getlantern/systray.nativeLoop(0x8a1083, 0x7, 0x400, 0x300)
        C:/Users/Administrator/Desktop/next/go/systray/systray_windows.go:44 +0x3e7
github.com/getlantern/systray.RunWithAppWindow(0x8a1083, 0x7, 0x400, 0x300, 0x8bf898, 0x8bf880)
        C:/Users/Administrator/Desktop/next/go/systray/systray.go:107 +0xb0
main.main()
        C:/Users/Administrator/Desktop/next/go/systray/example/main.go:20 +0x67


goroutine 1 [running, locked to thread]:
github.com/getlantern/systray.fail(...)
        C:/Users/Administrator/Desktop/next/go/systray/systray_windows.go:267
github.com/getlantern/systray.nativeLoop(0x8a1083, 0x7, 0x400, 0x300)
        C:/Users/Administrator/Desktop/next/go/systray/systray_windows.go:46 +0xd06
github.com/getlantern/systray.RunWithAppWindow(0x8a1083, 0x7, 0x400, 0x300, 0x8bf898, 0x8bf880)
        C:/Users/Administrator/Desktop/next/go/systray/systray.go:107 +0xb0
main.main()
        C:/Users/Administrator/Desktop/next/go/systray/example/main.go:20 +0x67
exit status 2

```

**Comment by oxtoacart** [comment]
You need to build a little differently, I've updated the README.

**Comment by Gemorroj** [comment]
#124
idk, didn't work for me
