### ISSUE TITLE
issue while i am calling the systray in mac version

### ISSUE THREAD

**Issue by rajkumarks7** [getlantern/systray#155]
2020-06-16 14:40:02.329 awesomeProject[16053:375576] *** Assertion failure in +[NSUndoManager _endTopLevelGroupings], /AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/Foundation/Foundation-1676.105/Foundation/Misc.subproj/NSUndoManager.m:363
2020-06-16 14:40:02.330 awesomeProject[16053:375576] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: '+[NSUndoManager(NSInternal) _endTopLevelGroupings] is only safe to invoke on the main thread.'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff318c2be7 __exceptionPreprocess + 250
	1   libobjc.A.dylib                     0x00007fff6a69a5bf objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff318ebd98 +[NSException raise:format:arguments:] + 88
	3   Foundation                          0x00007fff33fdae9d -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 191

**Comment by rajkumarks7** [comment]
fyne.io/fyne/internal/driver/glfw.(*gLDriver).runGL(0xc0000dcac0)
	/Users/sushma/go/src/fyne.io/fyne/internal/driver/glfw/loop.go:90 +0x1b0
fyne.io/fyne/internal/driver/glfw.(*gLDriver).Run(0xc0000dcac0)
	/Users/sushma/go/src/fyne.io/fyne/internal/driver/glfw/driver.go:71 +0x37
fyne.io/fyne/internal/driver/glfw.(*window).ShowAndRun(0xc0002749c0)
	/Users/sushma/go/src/fyne.io/fyne/internal/driver/glfw/window.go:387 +0x57
main.login()
	/Users/sushma/go/src/workahub/main.go:544 +0x6a4
main.main()
	/Users/sushma/go/src/workahub/main.go:96 +0x53

goroutine 19 [sleep]:
time.Sleep(0x22ecb25c00)
	/usr/local/go/src/runtime/time.go:188 +0xba
fyne.io/fyne/internal/painter.svgCacheJanitor.func1()
	/Users/sushma/go/src/fyne.io/fyne/internal/painter/svg_cache.go:51 +0x116
sync.(*Once).doSlow(0x53b2ee0, 0xc0000b0300)
	/usr/local/go/src/sync/once.go:66 +0xec
sync.(*Once).Do(0x53b2ee0, 0xc0000b0300)
	/usr/local/go/src/sync/once.go:57 +0x45
created by fyne.io/fyne/internal/painter.svgCacheJanitor
	/Users/sushma/go/src/fyne.io/fyne/internal/painter/svg_cache.go:49 +0x9b

goroutine 20 [chan receive]:
fyne.io/fyne/app.newAppWithDriver.func1(0xc00008e360, 0xc0000b49c0)
	/Users/sushma/go/src/fyne.io/fyne/app/app.go:113 +0x3d
created by fyne.io/fyne/app.newAppWithDriver
	/Users/sushma/go/src/fyne.io/fyne/app/app.go:111 +0x182

goroutine 21 [syscall]:
syscall.syscall6(0x44150f0, 0x6, 0x0, 0x0, 0xc000053e88, 0xa, 0x53b3010, 0x0, 0x0, 0x0)
	/usr/local/go/src/runtime/sys_darwin.go:74 +0x2e
fyne.io/fyne/vendor/golang.org/x/sys/unix.kevent(0x6, 0x0, 0x0, 0xc000053e88, 0xa, 0x53b3010, 0x0, 0x0, 0x0)
	/Users/sushma/go/src/fyne.io/fyne/vendor/golang.org/x/sys/unix/zsyscall_darwin_amd64.go:292 +0xa6
fyne.io/fyne/vendor/golang.org/x/sys/unix.Kevent(0x6, 0x0, 0x0, 0x0, 0xc000053e88, 0xa, 0xa, 0x53b3010, 0x0, 0x0, ...)
	/Users/sushma/go/src/fyne.io/fyne/vendor/golang.org/x/sys/unix/syscall_bsd.go:413 +0x71
fyne.io/fyne/vendor/github.com/fsnotify/fsnotify.read(0x6, 0xc000053e88, 0xa, 0xa, 0x53b3010, 0xc000053e88, 0x0, 0xa, 0x0, 0x0)
	/Users/sushma/go/src/fyne.io/fyne/vendor/github.com/fsnotify/fsnotify/kqueue.go:511 +0x6e
fyne.io/fyne/vendor/github.com/fsnotify/fsnotify.(*Watcher).readEvents(0xc0000b4a20)
	/Users/sushma/go/src/fyne.io/fyne/vendor/github.com/fsnotify/fsnotify/kqueue.go:274 +0x804
created by fyne.io/fyne/vendor/github.com/fsnotify/fsnotify.NewWatcher
	/Users/sushma/go/src/fyne.io/fyne/vendor/github.com/fsnotify/fsnotify/kqueue.go:62 +0x18f

goroutine 22 [chan receive]:
fyne.io/fyne/app.watchFile.func1(0xc0000b4a20, 0xc000176480, 0x34, 0xc0002b6120, 0xc0002b6130)
	/Users/sushma/go/src/fyne.io/fyne/app/settings_desktop.go:42 +0x58
created by fyne.io/fyne/app.watchFile
	/Users/sushma/go/src/fyne.io/fyne/app/settings_desktop.go:41 +0xe7

goroutine 23 [select, locked to thread]:
fyne.io/fyne/internal/driver/glfw.(*gLDriver).startDrawThread.func1(0xc00008e4e0, 0xc0000c84b0, 0xc0000dcac0)
	/Users/sushma/go/src/fyne.io/fyne/internal/driver/glfw/loop.go:173 +0x1a5
created by fyne.io/fyne/internal/driver/glfw.(*gLDriver).startDrawThread
	/Users/sushma/go/src/fyne.io/fyne/internal/driver/glfw/loop.go:169 +0xbd

goroutine 41 [runnable]:
fyne.io/fyne/internal/driver/glfw.(*window).destroy(0xc000211860, 0xc0000dcac0)
	/Users/sushma/go/src/fyne.io/fyne/internal/driver/glfw/window.go:440
created by fyne.io/fyne/internal/driver/glfw.(*gLDriver).runGL
	/Users/sushma/go/src/fyne.io/fyne/internal/driver/glfw/loop.go:119 +0x524

goroutine 25 [chan receive]:
fyne.io/fyne/internal/driver/glfw.(*glCanvas).setupThemeListener.func1(0xc00008e540, 0xc0000d1680)
	/Users/sushma/go/src/fyne.io/fyne/internal/driver/glfw/canvas.go:520 +0x47
created by fyne.io/fyne/internal/driver/glfw.(*glCanvas).setupThemeListener
	/Users/sushma/go/src/fyne.io/fyne/internal/driver/glfw/canvas.go:518 +0xa6

goroutine 8 [select]:
net/http.(*persistConn).writeLoop(0xc0001dcb40)
	/usr/local/go/src/net/http/transport.go:2277 +0x11c
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1648 +0xc7b

goroutine 6 [chan receive]:
fyne.io/fyne/internal/painter.SvgCacheMonitorTheme.func1(0xc000024120)
	/Users/sushma/go/src/fyne.io/fyne/internal/painter/svg_cache.go:103 +0x34
created by fyne.io/fyne/internal/painter.SvgCacheMonitorTheme
	/Users/sushma/go/src/fyne.io/fyne/internal/painter/svg_cache.go:101 +0x9c

goroutine 7 [IO wait]:
internal/poll.runtime_pollWait(0x56b0f40, 0x72, 0xffffffffffffffff)
	/usr/local/go/src/runtime/netpoll.go:203 +0x55
internal/poll.(*pollDesc).wait(0xc000128d98, 0x72, 0x1000, 0x1000, 0xffffffffffffffff)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc000128d80, 0xc000643000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:169 +0x201
net.(*netFD).Read(0xc000128d80, 0xc000643000, 0x1000, 0x1000, 0x403847c, 0xc00004eb70, 0x4061fa0)
	/usr/local/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc0000100a8, 0xc000643000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:184 +0x8e
net/http.(*persistConn).Read(0xc0001dcb40, 0xc000643000, 0x1000, 0x1000, 0xc0000252c0, 0xc00004ec70, 0x4007cd5)
	/usr/local/go/src/net/http/transport.go:1825 +0x75
bufio.(*Reader).fill(0xc000161860)
	/usr/local/go/src/bufio/bufio.go:100 +0x103
bufio.(*Reader).Peek(0xc000161860, 0x1, 0x0, 0x0, 0x1, 0xc000025200, 0x0)
	/usr/local/go/src/bufio/bufio.go:138 +0x4f
net/http.(*persistConn).readLoop(0xc0001dcb40)
	/usr/local/go/src/net/http/transport.go:1978 +0x1a8
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1647 +0xc56

goroutine 40 [chan receive]:
fyne.io/fyne/internal/driver/glfw.(*glCanvas).setupThemeListener.func1(0xc0001b0360, 0xc0001dcd80)
	/Users/sushma/go/src/fyne.io/fyne/internal/driver/glfw/canvas.go:520 +0x47
created by fyne.io/fyne/internal/driver/glfw.(*glCanvas).setupThemeListener
	/Users/sushma/go/src/fyne.io/fyne/internal/driver/glfw/canvas.go:518 +0xa6

goroutine 52 [chan receive]:
github.com/getlantern/systray.Register.func2(0xc000162240, 0x49bed80)
	/Users/sushma/go/src/github.com/getlantern/systray/systray.go:90 +0x34
created by github.com/getlantern/systray.Register
	/Users/sushma/go/src/github.com/getlantern/systray/systray.go:89 +0xdd

rax    0x0
rbx    0x7000043c9000
rcx    0x7000043c7578
rdx    0x0
rdi    0xf03
rsi    0x6
rbp    0x7000043c75a0
rsp    0x7000043c7578
r8     0x7000043c7440
r9     0x7000043c7610
r10    0x7000043c9000
r11    0x246
r12    0xf03
r13    0x3000000008
r14    0x6
r15    0x16
rip    0x7fff6914733a
rflags 0x246
cs     0x7
fs     0x0
gs     0x0
exit status 2

**Comment by JanezStupar** [comment]
I got the same issue @rajkumarks7 did you work it out somehow?

**Comment by rajkumarks7** [comment]
No

**Comment by JanezStupar** [comment]
@rajkumarks7 well... I found a way to do it in my environment (go-flutter) as it allows to execute code synchronously in main thread.

But I still had to use a different systray library for Macos - as `systray.Register` doesn't seem to work the way it should for some reason.

**Comment by rajkumarks7** [comment]
Cool can I know how to do it

**Comment by JanezStupar** [comment]
I can share the code used... This is the RPC entrypoint I am using: https://github.com/go-flutter-desktop/go-flutter/blob/47c327c03984e00b5bd571fcdb68faff958d451b/plugin/method-channel.go#L138

And this is the project I am working on: https://github.com/JanezStupar/flutter_systray

I would gladly help more, but there is a chance that you will be able to figure it out on your own quicker.

Just a brief description of what is going on to save you some time:
`Flutter` is a mutliplafrom application development platform.
`go-flutter-desktop` is a custom community developed embedder written in go that offers some features that official Flutter SDK hasn't gotten around to support yet, most importantly a very nice plugin system.
`flutter_systray` is 3rd party plugin for `go-flutter-desktop` written by me that gives Flutter apps systray menu support.

Also - do note that I had to (resort to this)[https://github.com/shurcooL/trayhost] library for MacOS.
