### ISSUE TITLE
Windows SetTooltip invalid memory address

### ISSUE THREAD

**Issue by psidex** [getlantern/systray#158]
```powershell
PS C:\Users\Simon\go\src\github.com\psidex\EACS> go run .\cmd\test\main.go
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x6608e6]

goroutine 6 [running]:
github.com/getlantern/systray.(*winTray).setTooltip(0x921fa0, 0x6f6138, 0x1d, 0xc000086058, 0xc0000311b8)
        C:/Users/Simon/go/pkg/mod/github.com/getlantern/systray@v1.0.3/systray_windows.go:226 +0x66
github.com/getlantern/systray.SetTooltip(0x6f6138, 0x1d)
        C:/Users/Simon/go/pkg/mod/github.com/getlantern/systray@v1.0.3/systray_windows.go:852 +0x4c
main.OnReady()
        C:/Users/Simon/go/src/github.com/psidex/EACS/cmd/test/main.go:8 +0x3d
github.com/getlantern/systray.Register.func2(0xc000014180, 0x706528)
        C:/Users/Simon/go/pkg/mod/github.com/getlantern/systray@v1.0.3/systray.go:91 +0x45
created by github.com/getlantern/systray.Register
        C:/Users/Simon/go/pkg/mod/github.com/getlantern/systray@v1.0.3/systray.go:89 +0xe3
exit status 2
```

here is the contents of `main.go`:

```go
package main

import (
	"github.com/getlantern/systray"
)

func OnReady() {
	systray.SetTooltip("This is the tooltip text")
}

func OnExit() {
	// No cleanup needed.
}

func main() {
	systray.Run(OnReady, OnExit)
}

```

**Comment by ldstein** [comment]
FWIW, I'm also experiencing this issue.

I'm observing if I run the compiled exe 6-7 times, ~30% will fail with the same error.

v0.9.0 doesn't appear to be affected. 1.0.0, 1.0.1, 1.0.2 and 1.0.3 exhibit this issue.

Tested with:
- Windows 10 x64
- Go 1.14.1
- TDC-GCC 5.1.0-2 and TDM-GCC 9.2.0

**Comment by gravataLonga** [comment]
@joesis @oxtoacart How and where can i fix this?  

```
ERROR systray: systray_windows.go:795 Unable to set icon: Unspecified error [error=Unable to set icon: %v error_location=github.com/getlantern/systray.SetIcon (systray_windows.go:795) error_op= error_text=Unable to set icon: Uns
pecified error error_type=errors.Error]
ERROR systray: systray_windows.go:795   at github.com/getlantern/systray.SetIcon (systray_windows.go:795)
ERROR systray: systray_windows.go:795   at main.onReady (main.go:48)
ERROR systray: systray_windows.go:795   at github.com/getlantern/systray.Register.func2 (systray.go:91)
ERROR systray: systray_windows.go:795   at runtime.goexit (asm_amd64.s:1373)
ERROR systray: systray_windows.go:795 Caused by: Unspecified error
ERROR systray: systray_windows.go:861 Unable to addOrUpdateMenuItem: Invalid menu handle. [error=Unable to addOrUpdateMenuItem: %v error_location=github.com/getlantern/systray.addOrUpdateMenuItem (systray_windows.go:861) error_o
p= error_text=Unable to addOrUpdateMenuItem: Invalid menu handle. error_type=errors.Error]
ERROR systray: systray_windows.go:861   at github.com/getlantern/systray.addOrUpdateMenuItem (systray_windows.go:861)
ERROR systray: systray_windows.go:861   at github.com/getlantern/systray.(*MenuItem).update (systray.go:194)
ERROR systray: systray_windows.go:861   at github.com/getlantern/systray.AddMenuItem (systray.go:116)
ERROR systray: systray_windows.go:861   at main.onReady (main.go:52)
ERROR systray: systray_windows.go:861   at github.com/getlantern/systray.Register.func2 (systray.go:91)
ERROR systray: systray_windows.go:861   at runtime.goexit (asm_amd64.s:1373)
ERROR systray: systray_windows.go:861 Caused by: Invalid menu handle.
ERROR systray: systray_windows.go:844 Unable to addOrUpdateMenuItem: Invalid menu handle. [error=Unable to addOrUpdateMenuItem: %v error_location=github.com/getlantern/systray.(*MenuItem).SetIcon (systray_windows.go:844) error_o
p= error_text=Unable to addOrUpdateMenuItem: Invalid menu handle. error_type=errors.Error]
ERROR systray: systray_windows.go:844   at github.com/getlantern/systray.(*MenuItem).SetIcon (systray_windows.go:844)
ERROR systray: systray_windows.go:844   at main.onReady (main.go:53)
ERROR systray: systray_windows.go:844   at github.com/getlantern/systray.Register.func2 (systray.go:91)
ERROR systray: systray_windows.go:844   at runtime.goexit (asm_amd64.s:1373)
ERROR systray: systray_windows.go:844 Caused by: Invalid menu handle.
ERROR systray: systray_windows.go:877 Unable to addSeparator: Invalid menu handle. [error=Unable to addSeparator: %v error_location=github.com/getlantern/systray.addSeparator (systray_windows.go:877) error_op= error_text=Unable
to addSeparator: Invalid menu handle. error_type=errors.Error]
ERROR systray: systray_windows.go:877   at github.com/getlantern/systray.addSeparator (systray_windows.go:877)
ERROR systray: systray_windows.go:877   at github.com/getlantern/systray.AddSeparator (systray.go:122)
ERROR systray: systray_windows.go:877   at main.onReady (main.go:54)
ERROR systray: systray_windows.go:877   at github.com/getlantern/systray.Register.func2 (systray.go:91)
ERROR systray: systray_windows.go:877   at runtime.goexit (asm_amd64.s:1373)
ERROR systray: systray_windows.go:877 Caused by: Invalid menu handle.
ERROR systray: systray_windows.go:861 Unable to addOrUpdateMenuItem: Invalid menu handle. [error=Unable to addOrUpdateMenuItem: %v error_location=github.com/getlantern/systray.addOrUpdateMenuItem (systray_windows.go:861) error_o
p= error_text=Unable to addOrUpdateMenuItem: Invalid menu handle. error_type=errors.Error]
ERROR systray: systray_windows.go:861   at github.com/getlantern/systray.addOrUpdateMenuItem (systray_windows.go:861)
ERROR systray: systray_windows.go:861   at github.com/getlantern/systray.(*MenuItem).update (systray.go:194)
ERROR systray: systray_windows.go:861   at github.com/getlantern/systray.AddMenuItem (systray.go:116)
ERROR systray: systray_windows.go:861   at main.onReady (main.go:56)
ERROR systray: systray_windows.go:861   at github.com/getlantern/systray.Register.func2 (systray.go:91)
ERROR systray: systray_windows.go:861   at runtime.goexit (asm_amd64.s:1373)
ERROR systray: systray_windows.go:861 Caused by: Invalid menu handle.
ERROR systray: systray_windows.go:844 Unable to addOrUpdateMenuItem: Invalid menu handle. [error=Unable to addOrUpdateMenuItem: %v error_location=github.com/getlantern/systray.(*MenuItem).SetIcon (systray_windows.go:844) error_o
p= error_text=Unable to addOrUpdateMenuItem: Invalid menu handle. error_type=errors.Error]
ERROR systray: systray_windows.go:844   at github.com/getlantern/systray.(*MenuItem).SetIcon (systray_windows.go:844)
ERROR systray: systray_windows.go:844   at main.onReady (main.go:57)
ERROR systray: systray_windows.go:844   at github.com/getlantern/systray.Register.func2 (systray.go:91)
ERROR systray: systray_windows.go:844   at runtime.goexit (asm_amd64.s:1373)
ERROR systray: systray_windows.go:844 Caused by: Invalid menu handle.
ERROR systray: systray_windows.go:877 Unable to addSeparator: Invalid menu handle. [error=Unable to addSeparator: %v error_location=github.com/getlantern/systray.addSeparator (systray_windows.go:877) error_op= error_text=Unable
to addSeparator: Invalid menu handle. error_type=errors.Error]
ERROR systray: systray_windows.go:877   at github.com/getlantern/systray.addSeparator (systray_windows.go:877)
ERROR systray: systray_windows.go:877   at github.com/getlantern/systray.AddSeparator (systray.go:122)
ERROR systray: systray_windows.go:877   at main.onReady (main.go:58)
ERROR systray: systray_windows.go:877   at github.com/getlantern/systray.Register.func2 (systray.go:91)
ERROR systray: systray_windows.go:877   at runtime.goexit (asm_amd64.s:1373)
ERROR systray: systray_windows.go:877 Caused by: Invalid menu handle.
ERROR systray: systray_windows.go:861 Unable to addOrUpdateMenuItem: Invalid menu handle. [error=Unable to addOrUpdateMenuItem: %v error_location=github.com/getlantern/systray.addOrUpdateMenuItem (systray_windows.go:861) error_o
p= error_text=Unable to addOrUpdateMenuItem: Invalid menu handle. error_type=errors.Error]
ERROR systray: systray_windows.go:861   at github.com/getlantern/systray.addOrUpdateMenuItem (systray_windows.go:861)
ERROR systray: systray_windows.go:861   at github.com/getlantern/systray.(*MenuItem).update (systray.go:194)
ERROR systray: systray_windows.go:861   at github.com/getlantern/systray.AddMenuItem (systray.go:116)
ERROR systray: systray_windows.go:861   at main.onReady (main.go:60)
ERROR systray: systray_windows.go:861   at github.com/getlantern/systray.Register.func2 (systray.go:91)
ERROR systray: systray_windows.go:861   at runtime.goexit (asm_amd64.s:1373)
ERROR systray: systray_windows.go:861 Caused by: Invalid menu handle.
ERROR systray: systray_windows.go:844 Unable to addOrUpdateMenuItem: Invalid menu handle. [error=Unable to addOrUpdateMenuItem: %v error_location=github.com/getlantern/systray.(*MenuItem).SetIcon (systray_windows.go:844) error_o
p= error_text=Unable to addOrUpdateMenuItem: Invalid menu handle. error_type=errors.Error]
ERROR systray: systray_windows.go:844   at github.com/getlantern/systray.(*MenuItem).SetIcon (systray_windows.go:844)
ERROR systray: systray_windows.go:844   at main.onReady (main.go:62)
ERROR systray: systray_windows.go:844   at github.com/getlantern/systray.Register.func2 (systray.go:91)
ERROR systray: systray_windows.go:844   at runtime.goexit (asm_amd64.s:1373)
ERROR systray: systray_windows.go:844 Caused by: Invalid menu handle.

```   

It's anoying and isn't working on windows!

**Comment by joesis** [comment]
How does the latest master (v1.0.4) works to you guys?

**Comment by ldstein** [comment]
Can't comment on v1.0.4 specifically, but have been giving  [4c7e35b4e5114211b7c7c3b57484c56de802767a](https://github.com/getlantern/systray/commit/4c7e35b4e5114211b7c7c3b57484c56de802767a) a good workout for the last couple of days. Fixed all the issues for me.

**Comment by gravataLonga** [comment]
Appears working, but i got other issue i think not related to this. 
![image](https://user-images.githubusercontent.com/1126525/88275958-24c24300-ccd6-11ea-9b88-c1b99cb1afb9.png)

**Comment by joesis** [comment]
@gravataLonga you mean the icons of the menu items? Probably play with the image format a bit though I don't have much experience on that.

**Comment by gravataLonga** [comment]
@joesis thank you for your time. Yeah, need to play a little bit more. For me you can close this issue it's working now!

**Comment by psidex** [comment]
I'm still experiencing the same error on 1.0.4 (using the same code in my initial issue)

```powershell
PS C:\Users\Simon\go\src\github.com\psidex\trayTest> go run .\main.go
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x6608ae]

goroutine 6 [running]:
github.com/getlantern/systray.(*winTray).setTooltip(0x923260, 0x6f5060, 0x18, 0x0, 0x0)
        C:/Users/Simon/go/pkg/mod/github.com/getlantern/systray@v1.0.4/systray_windows.go:238 +0xce
github.com/getlantern/systray.SetTooltip(0x6f5060, 0x18)
        C:/Users/Simon/go/pkg/mod/github.com/getlantern/systray@v1.0.4/systray_windows.go:899 +0x4c
main.OnReady()
        C:/Users/Simon/go/src/github.com/psidex/trayTest/main.go:8 +0x3d
github.com/getlantern/systray.Register.func2(0xc000014180, 0x7075d0)
        C:/Users/Simon/go/pkg/mod/github.com/getlantern/systray@v1.0.4/systray.go:91 +0x45
created by github.com/getlantern/systray.Register
        C:/Users/Simon/go/pkg/mod/github.com/getlantern/systray@v1.0.4/systray.go:89 +0xe3
exit status 2
```

**Comment by gravataLonga** [comment]
@joesis for any one that want to put icon on your systray on windows, the image must be 32px and converted to .ico. Then i used `https://github.com/cratonica/2goarray` to convert to array of bytes.

**Comment by psidex** [comment]
I am also getting an `Invalid menu handle` error when using `AddMenuItem` before using `SetIcon`.

All of these issues seem to be linked to something that `SetIcon` does?

**Comment by joesis** [comment]
Interesting @psidex the panic means an nil pointer but neither parameters to `copy` at  https://github.com/getlantern/systray/blob/33b837f4b94ed5204e30b0379251ff73ed4913a4/systray_windows.go#L238 can be nil at the point. `t.nid` is an pointer but it [is initialized](https://github.com/getlantern/systray/blob/33b837f4b94ed5204e30b0379251ff73ed4913a4/systray_windows.go#L425) as part of register process.

**Comment by Etua** [comment]
My program would crash about 50% of the time because of this issue until I started adding 500ms delay before calling _setToolTip_ as suggested by @ldstein in #164 and it seems to have worked. Why you ask? I have no idea but there is something glitchy going inside the library.

**Comment by gravataLonga** [comment]
Sorry, why comment's was deleted? Only for curiosity..

**Comment by leejoys** [comment]
This way it's working:

`func main() {
	systray.Run(onReady, onExit)
}

func onReady() {
	systray.SetTitle("Sup")
	systray.SetIcon(ico)
	systray.SetTooltip("Sup")
}

func onExit() {

}
`

But this way fall to panic:

`func main() {
	systray.Run(onReady, onExit)
}

func onReady() {
	systray.SetTitle("Sup")
	systray.SetTooltip("Sup")
	systray.SetIcon(ico)

}

func onExit() {

}
`
