### ISSUE TITLE
Crash when registering with WebView

### ISSUE THREAD

**Issue by Firaenix** [getlantern/systray#163]
Hi, 

I've been using this systray module for a while and it has been fantastic, however I also want to use it in conjunction with https://github.com/webview/webview. However when I run them in parallel, my code crashes.

I'm far from an expert at golang, but I would really appreciate some help, especially when I can see the webview example in this repo.

Here is some example code based on the example in this repo:

```golang package main

import (
	"github.com/getlantern/systray"
	"github.com/getlantern/systray/example/icon"
	"github.com/webview/webview"
)
var view webview.WebView

func main() {
	systray.Register(onReady, nil)
	view = webview.New(true)
	defer view.Destroy()
	view.SetTitle("Test")
	view.SetSize(800, 600, webview.HintNone)
	view.Run()
}

func onReady() {
	systray.SetTemplateIcon(icon.Data, icon.Data)
	systray.SetTitle("Webview example")
	mShowGoogle := systray.AddMenuItem("Show Google", "")
	mQuit := systray.AddMenuItem("Quit", "Quit the whole app")
	go func() {
		for {
			select {
			case <-mShowGoogle.ClickedCh:
				view.Navigate("https://google.com")
			case <-mQuit.ClickedCh:
				systray.Quit()
			}
		}
	}()

}

Error:

❯ go run . 
# github.com/getlantern/systray/webview_example
ld: warning: ignoring file rsrc.syso, building for macOS-x86_64 but attempting to link with file built for unknown-unsupported file format ( 0x4C 0x01 0x01 0x00 0x00 0x00 0x00 0x00 0xFF 0x03 0x00 0x00 0x01 0x00 0x00 0x00 )
# github.com/getlantern/systray/webview_example
ld: warning: ignoring file /var/folders/km/7732wjsx66b0zm9l3tpxdky40000gn/T/go-link-200901635/000003.o, building for macOS-x86_64 but attempting to link with file built for unknown-unsupported file format ( 0x4C 0x01 0x01 0x00 0x00 0x00 0x00 0x00 0xFF 0x03 0x00 0x00 0x01 0x00 0x00 0x00 )
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x7fff6d542c25]

runtime stack:
runtime.throw(0x43c7195, 0x2a)
        /usr/local/go/src/runtime/panic.go:774 +0x72
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_unix.go:378 +0x47c

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x42ff8a0, 0xc000058e90, 0xc000000180)
        /usr/local/go/src/runtime/cgocall.go:128 +0x5b fp=0xc000058e60 sp=0xc000058e28 pc=0x400553b
github.com/webview/webview._Cfunc_webview_create(0x1, 0x0, 0x0)
        _cgo_gotypes.go:120 +0x4e fp=0xc000058e90 sp=0xc000058e60 pc=0x42fabee
github.com/webview/webview.NewWindow.func1(0x4366d01, 0x0, 0xc00463891d)
        /Users/firaenix/Projects/go/pkg/mod/github.com/webview/webview@v0.0.0-20200724072439-e0c01595b361/webview.go:162 +0x5f fp=0xc000058ec8 sp=0xc000058e90 pc=0x42fc3df
github.com/webview/webview.NewWindow(0x403d601, 0x0, 0xc000000180, 0xc000058f50)
        /Users/firaenix/Projects/go/pkg/mod/github.com/webview/webview@v0.0.0-20200724072439-e0c01595b361/webview.go:162 +0x4e fp=0xc000058ef8 sp=0xc000058ec8 pc=0x42fb4de
github.com/webview/webview.New(...)
        /Users/firaenix/Projects/go/pkg/mod/github.com/webview/webview@v0.0.0-20200724072439-e0c01595b361/webview.go:152
main.main()
        /Users/firaenix/Projects/systray/webview_example/main.go:12 +0x3a fp=0xc000058f60 sp=0xc000058ef8 pc=0x42fdb1a
runtime.main()
        /usr/local/go/src/runtime/proc.go:203 +0x21e fp=0xc000058fe0 sp=0xc000058f60 pc=0x403169e
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc000058fe8 sp=0xc000058fe0 pc=0x405c191
exit status 2```

**Comment by yusufhm** [comment]
Hey @Firaenix were you able to find a solution to this? I'm running into the same problem.

**Comment by Firaenix** [comment]
No, I havent been able to unfortunately

**Comment by prashantgupta24** [comment]
Even I am not able to make it work with webview. 

I tried fyne, (fyne.io), and at least it doesn't crash on start up, it shows the fyne ui. But unfortunately the systray doesn't show up.

```
package main

import (
	"fmt"

	"fyne.io/fyne/app"
	"fyne.io/fyne/widget"
	"github.com/getlantern/systray"
	"github.com/go-clip/icon"
)

func main() {
	systray.Register(onReady, func() {})
	// app.Start()

	a := app.New()
	w := a.NewWindow("Hello")

	hello := widget.NewLabel("Hello Fyne!")
	w.SetContent(widget.NewVBox(
		hello,
		widget.NewButton("Hi!", func() {
			hello.SetText("Welcome :)")
		}),
	))

	w.ShowAndRun()
}

func onReady() {
	systray.SetTemplateIcon(icon.Data, icon.Data)
	systray.SetTitle("Webview example")
	mShowGoogle := systray.AddMenuItem("Show Google", "")
	mQuit := systray.AddMenuItem("Quit", "Quit the whole app")
	go func() {
		for {
			select {
			case <-mShowGoogle.ClickedCh:
				fmt.Println("clicked")
			case <-mQuit.ClickedCh:
				systray.Quit()
			}
		}
	}()

}
```
