### ISSUE TITLE
[help] crash runtime: unknown pc 0x7f3e7dca37bb

### ISSUE THREAD

**Issue by ngxlua** [getlantern/systray#189]
I try to run `getlantern/systray/webview_example`

env: 
```
system:
lsb_release -a
No LSB modules are available.
Distributor ID: Deepin
Description:    Deepin 20
Release:        20
Codename:       n/a

```

error:
```
$ ./webview_example 

(webview_example:4016): GLib-GObject-CRITICAL **: 15:37:52.525: g_value_set_boxed: assertion 'G_VALUE_HOLDS_BOXED (value)' failed

(webview_example:4016): Gtk-WARNING **: 15:37:52.541: Theme parsing error: gtk.css:3611:22: 'none' is not a valid color name
SIGABRT: abort
PC=0x7f3e7dca37bb m=3 sigcode=18446744073709551610

goroutine 0 [idle]:
runtime: unknown pc 0x7f3e7dca37bb
stack: frame={sp:0x7f3e52aa6430, fp:0x0} stack=[0x7f3e522a6f08,0x7f3e52aa6b08)
00007f3e52aa6330:  00007f3e7dfefa20  0000000000000000 
00007f3e52aa6340:  0000000000000000  00007f3e8324939f 
00007f3e52aa6350:  000000000000000e  0000000000000000 
00007f3e52aa6360:  0000000000000005  0000000000000000 
00007f3e52aa6370:  0000000000000001  00007f3e7dfefa20 
00007f3e52aa6380:  00007f3e7de6da47  0000000100000000 
00007f3e52aa6390:  00007f3e52aa63c0  00007f3e52aa63d0 
00007f3e52aa63a0:  00007f3e7dfefd80  0000000000000000 
00007f3e52aa63b0:  00007f3e52aa6408  0000000000000007 
00007f3e52aa63c0:  00000000ffffffff  000080c000080000 
00007f3e52aa63d0:  00007f3e7de85808  00007f3e7dfef510 
00007f3e52aa63e0:  0000000000000020  0000000000000000 
00007f3e52aa63f0:  0000000000000007  0000000000000030 
00007f3e52aa6400:  0000000000000003  00007f3e440008d8 
00007f3e52aa6410:  000000000000001f  0000000000000050 
00007f3e52aa6420:  ffffffffffffffa8  0000000000000000 
00007f3e52aa6430: <0000000000000000  0000000000000000 
00007f3e52aa6440:  0000000000000000  0000006e0000005b 
00007f3e52aa6450:  000000770000007c  00007f3e7f230b9d 
00007f3e52aa6460:  0000000000000000  00007f3e7f238d20 
00007f3e52aa6470:  00007f3e7f569808  fa9841f0d300e000 
00007f3e52aa6480:  ffffffffffffffa8  00007f3e501023f0 
00007f3e52aa6490:  00007f3e50335000  00007f3e7f235fba 
00007f3e52aa64a0:  0000000000000020  0000000000001000 
00007f3e52aa64b0:  fffffffe7fffffff  ffffffffffffffff 
00007f3e52aa64c0:  ffffffffffffffff  ffffffffffffffff 
00007f3e52aa64d0:  ffffffffffffffff  ffffffffffffffff 
00007f3e52aa64e0:  ffffffffffffffff  ffffffffffffffff 
00007f3e52aa64f0:  ffffffffffffffff  ffffffffffffffff 
00007f3e52aa6500:  ffffffffffffffff  ffffffffffffffff 
00007f3e52aa6510:  ffffffffffffffff  ffffffffffffffff 
00007f3e52aa6520:  ffffffffffffffff  ffffffffffffffff 
runtime: unknown pc 0x7f3e7dca37bb
stack: frame={sp:0x7f3e52aa6430, fp:0x0} stack=[0x7f3e522a6f08,0x7f3e52aa6b08)
00007f3e52aa6330:  00007f3e7dfefa20  0000000000000000 
00007f3e52aa6340:  0000000000000000  00007f3e8324939f 
00007f3e52aa6350:  000000000000000e  0000000000000000 
00007f3e52aa6360:  0000000000000005  0000000000000000 
00007f3e52aa6370:  0000000000000001  00007f3e7dfefa20 
00007f3e52aa6380:  00007f3e7de6da47  0000000100000000 
00007f3e52aa6390:  00007f3e52aa63c0  00007f3e52aa63d0 
00007f3e52aa63a0:  00007f3e7dfefd80  0000000000000000 
00007f3e52aa63b0:  00007f3e52aa6408  0000000000000007 
00007f3e52aa63c0:  00000000ffffffff  000080c000080000 
00007f3e52aa63d0:  00007f3e7de85808  00007f3e7dfef510 
00007f3e52aa63e0:  0000000000000020  0000000000000000 
00007f3e52aa63f0:  0000000000000007  0000000000000030 
00007f3e52aa6400:  0000000000000003  00007f3e440008d8 
00007f3e52aa6410:  000000000000001f  0000000000000050 
00007f3e52aa6420:  ffffffffffffffa8  0000000000000000 
00007f3e52aa6430: <0000000000000000  0000000000000000 
00007f3e52aa6440:  0000000000000000  0000006e0000005b 
00007f3e52aa6450:  000000770000007c  00007f3e7f230b9d 
00007f3e52aa6460:  0000000000000000  00007f3e7f238d20 
00007f3e52aa6470:  00007f3e7f569808  fa9841f0d300e000 
00007f3e52aa6480:  ffffffffffffffa8  00007f3e501023f0 
00007f3e52aa6490:  00007f3e50335000  00007f3e7f235fba 
00007f3e52aa64a0:  0000000000000020  0000000000001000 
00007f3e52aa64b0:  fffffffe7fffffff  ffffffffffffffff 
00007f3e52aa64c0:  ffffffffffffffff  ffffffffffffffff 
00007f3e52aa64d0:  ffffffffffffffff  ffffffffffffffff 
00007f3e52aa64e0:  ffffffffffffffff  ffffffffffffffff 
00007f3e52aa64f0:  ffffffffffffffff  ffffffffffffffff 
00007f3e52aa6500:  ffffffffffffffff  ffffffffffffffff 
00007f3e52aa6510:  ffffffffffffffff  ffffffffffffffff 
00007f3e52aa6520:  ffffffffffffffff  ffffffffffffffff 

goroutine 18 [syscall]:
runtime.cgocall(0x58c660, 0xc00003c6e0, 0x1a)
        /opt/go/src/runtime/cgocall.go:133 +0x5b fp=0xc00003c6b0 sp=0xc00003c678 pc=0x4070bb
main._Cfunc_showAppWindow(0x7f3e44002ab0)
        _cgo_gotypes.go:90 +0x45 fp=0xc00003c6e0 sp=0xc00003c6b0 pc=0x58c305
main.showWebview(0x5e6adc, 0x1a)
       go/src/github.com/getlantern/systray/webview_example/webview_nonwindows.go:19 +0x45 fp=0xc00003c708 sp=0xc00003c6e0 pc=0x58c485
main.onReady.func1(0xc000092000, 0xc000092040, 0xc000092080)
       go/src/github.com/getlantern/systray/webview_example/main.go:23 +0x154 fp=0xc00003c7c8 sp=0xc00003c708 pc=0x58c5f4
runtime.goexit()
        /opt/go/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc00003c7d0 sp=0xc00003c7c8 pc=0x46c201
created by main.onReady
        go/src/github.com/getlantern/systray/webview_example/main.go:19 +0x11f

goroutine 1 [syscall, locked to thread]:
main._Cfunc_configureAppWindow(0x20ed950, 0x30000000400)
        _cgo_gotypes.go:75 +0x45
main.configureWebview(0x5e2f7f, 0xf, 0x400, 0x300)
       go/src/github.com/getlantern/systray/webview_example/webview_nonwindows.go:15 +0x55
main.main()
        go/src/github.com/getlantern/systray/webview_example/main.go:10 +0x65

rax    0x0
rbx    0x6
rcx    0x7f3e7dca37bb
rdx    0x0
rdi    0x2
rsi    0x7f3e52aa6430
rbp    0x7f3e501f2000
rsp    0x7f3e52aa6430
r8     0x0
r9     0x7f3e52aa6430
r10    0x8
r11    0x246
r12    0x7f3e501e5000
r13    0x0
r14    0x7f3e501e5000
r15    0x0
rip    0x7f3e7dca37bb
rflags 0x246
cs     0x33
fs     0x0
gs     0x0

```

**Comment by ngxlua** [comment]
I have installed the following packages as prompted by the readme:

```
apt-get install gcc libgtk-3-dev libappindicator3-dev libwebkit2gtk-4.0-dev
```
